Initial action implementation
medigateio/trigger-circleci-pipeline pull request #1
Opened 2021-11-14 12:54 UTC by OrBin

2021-11-14 16:37 UTC, sharonyogev requested changes

2021-11-14 16:37 UTC, sharonyogev commented on action.yml
> +          GITHUB_REPOSITORY: ${{ github.repository }}
don't you want to make these 2 also an input? or maybe input with defaults?

2021-11-14 17:11 UTC, sharonyogev requested changes

2021-11-14 17:11 UTC, sharonyogev commented on trigger_circleci_pipeline.sh
> +            return 3
```suggestion
            exit 3
```

2021-11-14 17:11 UTC, sharonyogev commented on trigger_circleci_pipeline.sh
> +      return 4
```suggestion
      exit 4
```

2021-11-15 09:52 UTC, sharonyogev approved these changes

2021-11-15 10:14 UTC, merged

2021-11-15 10:14 UTC, OrBin commented
Tagged new version as `v1` and `v1.0`